### ISSUE TITLE
libpcap error: socket: Operation not permitted

### ISSUE THREAD

**Issue by GopherJ** [kpcyrd/sniffglue#52]
Hello, when I run `sniffglue` like in README.md
```bash
sniffglue `ip addr | awk '/state UP/ {print $2}' | sed 's/.$//'`
```
I got an error:
```bash
Failed to open interface "xxxx": libpcap error: socket: Operation not permitted
```
I have to use : 
```bash
sudo `which sniffglue`  `ip addr | awk '/state UP/ {print $2}' | sed 's/.$//'`
```
Do I need to run as root every time?

**Comment by kpcyrd** [comment]
Yes. Opening the interface for raw network access is a privileged operation, after all you don't want any user to be able to sniff your network.

```
sudo `which sniffglue`
```
This syntax is required due to PATH issues, which is unfortunate, depending on your system you could check if there's a package available, I'm working on getting it in debian and ubuntu.

You could try copying the binary to `/usr/local/bin`.

```
`ip addr | awk '/state UP/ {print $2}' | sed 's/.$//'`
```
Try dropping this, it's selecting an interface for you if you start it without any arguments. :)

**Comment by GopherJ** [comment]
Thanks for your quick reply! I'll close this and It's so cool sniffglue!
